//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combo
    {
        public Combo()
        {
        }

        public Combo(int iD, string image, string combo_Name, string product_List, DateTime startDate, DateTime endDate, double totalMoney, int discount)
        {
            ID = iD;
            Image = image;
            Combo_Name = combo_Name;
            Product_List = product_List;
            this.startDate = startDate;
            this.endDate = endDate;
            this.totalMoney = totalMoney;
            this.discount = discount;
        }

        public int ID { get; set; }
        public string Image { get; set; }
        public string Combo_Name { get; set; }
        public string Product_List { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public double totalMoney { get; set; }
        public int discount { get; set; }
    }
}
