//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public decimal totalMoney { get; set; }
        public System.DateTime createdDate { get; set; }
        public string customerAddress { get; set; }
    }
}
