//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
        }

        public Order(int iD, DateTime Date, double Total_Price, int Customer_Id, int Status)
        {
            ID = iD;
            this.Date = Date;
            this.Total_Price = Total_Price;
            this.Customer_Id = Customer_Id;
            this.Status = Status;
        }

        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
