//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {

        }
        public OrderDetail(int iD, int? order_Id, int? product_Id, int? combo_Id, int? quantity, double? price)
        {
            ID = iD;
            Order_Id = order_Id;
            Product_Id = product_Id;
            Combo_Id = combo_Id;
            Quantity = quantity;
            Price = price;
        }

        public int ID { get; set; }
        public Nullable<int> Order_Id { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Combo_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
