//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
        }

        public Order(int iD, DateTime? date, double? total_Price, int? user_Id, int? status)
        {
            ID = iD;
            Date = date;
            Total_Price = total_Price;
            User_Id = user_Id;
            Status = status;
        }

        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
