//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Product_Name { get; set; }
        public int Catalog_ID { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountMoney { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Brand_ID { get; set; }
    }
}
